huggingface/api-inference-community

.github/workflows/python-api-adapter-transformers.yaml, .github/workflows/python-api-allennlp.yaml, .github/workflows/python-api-create-merge-issue.yaml, .github/workflows/python-api-doctr.yaml, .github/workflows/python-api-espnet.yaml, .github/workflows/python-api-fairseq.yaml, .github/workflows/python-api-fasttext.yaml, .github/workflows/python-api-generic.yaml, .github/workflows/python-api-keras.yaml, .github/workflows/python-api-pyannote.yaml, .github/workflows/python-api-quality.yaml, .github/workflows/python-api-sentence-transformers.yaml, .github/workflows/python-api-spacy.yaml, .github/workflows/python-api-speechbrain.yaml, .github/workflows/python-api-stanza.yaml, .github/workflows/python-api-tests.yaml
Updating the workflows so hopefully they work again.
This was done with sed magic, so no files should have been forgotten.
=> Adapting all workflows.

manage.py
--model-id=XX/XXX becomes XX/XXX (simpler CLI).
=> `--model-id=XX/XXX` becomes `XX/XXX` (simpler CLI).

docker_images/speechbrain/app/pipelines/text_to_speech.py
Example text is not all there is
=> Fix SpeechBrain TTS

.github/workflows/python-api-quality.yaml, tests/test_dockers.py
Quality checks were not working anymore since GH removed ubuntu-18 support.
=> Upgrade GH action to ubuntu-20.

docker_images/pyannote/requirements.txt, tests/test_dockers.py
pyannote.audio integration seems to be broken: models takes forever to load, ending up in a time out.
This is a (desperate) attempt at fixing this...
=> Fixing pyannote.audio integration

docker_images/common/app/pipelines/text2text_generation.py, docker_images/common/tests/test_api_text2text_generation.py
This also adds templates to common to avoid this in the future
=> Fix SpeechBrain text generation

docker_images/nemo/requirements.txt
NEed to be merged after #123 
Fixes #122
=> Triggering a nemo CD.

docker_images/fairseq/requirements.txt
Update fairseq version to include https://github.com/facebookresearch/fairseq/commit/d47119871c2ac9a0a0aa2904dd8cfc1929b113d9
=> Update fairseq version in requirements.txt

docker_images/sklearn/requirements.txt
Somehow the old PR didn't trigger the CD (I'm guessing we should have rebased for the GH action to be visible :( )
=> Trigger CD ?

docker_images/diffusers/app/pipelines/text_to_image.py, docker_images/diffusers/requirements.txt
Make sure we pass custom scheduler
=> Speed up Stable Diffusion

.github/workflows/python-api-diffusers-cd.yaml, docker_images/diffusers/requirements.txt
This is already live, but cleaning things up and this PR will check that the CD finally works properly.
=> Fixing diffusers (we need transformers main to fix the CLIPProcessor issue).

docker_images/diffusers/Dockerfile, docker_images/diffusers/app/pipelines/text_to_image.py
How to prebuild `xformers`.
```
pip install torch==1.13.0
pip install ninja
git clone https://github.com/facebookresearch/xformers
cd xformers
git checkout 7e4c02c
git submodule update --init --recursive
python setup.py bdist_wheel
```
=> Enalbing xformers speedup + channel_last.

docker_images/sklearn/app/pipelines/common.py
Related to #136 when config is invalid it's not raised so I raised an error.
=> Raise errors when config is invalid for sklearn models

.github/workflows/python-api-paddlenlp-cd.yaml, .github/workflows/python-api-paddlenlp.yaml, docker_images/paddlenlp/Dockerfile, docker_images/paddlenlp/app/main.py, docker_images/paddlenlp/app/pipelines/__init__.py, docker_images/paddlenlp/app/pipelines/base.py, docker_images/paddlenlp/app/pipelines/conversational.py, docker_images/paddlenlp/app/pipelines/fill_mask.py, docker_images/paddlenlp/prestart.sh, docker_images/paddlenlp/requirements.txt, docker_images/paddlenlp/tests/test_api.py, docker_images/paddlenlp/tests/test_api_conversational.py, docker_images/paddlenlp/tests/test_api_fill_mask.py, docker_images/paddlenlp/tests/test_docker_build.py, tests/test_dockers.py
- Docker build successfully. Manually tested the generated paddlenlp docker image 
- Todo:  add `fill-mask` task once the paddlenlp can directly load from hf hub
=> Integrating PaddleNLP to HF Inference API

docker_images/common/app/pipelines/conversational.py, docker_images/common/app/pipelines/fill_mask.py, docker_images/paddlenlp/requirements.txt
- Pin paddlenlp version
- Fix fill_mask output format
- contribute `conversational` and `fill-mask` task back to `common` folder
=> [PaddleNLP] Pin paddlenlp version and fix fill_mask output format

docker_images/diffusers/app/pipelines/text_to_image.py, docker_images/diffusers/requirements.txt
Pin diffusers to 0.9.0 for now and improve pipeline to give better quality
=> [Text-to-image] Improve pipeline

docker_images/common/app/pipelines/summarization.py, docker_images/common/tests/test_api_summarization.py, docker_images/paddlenlp/app/main.py, docker_images/paddlenlp/app/pipelines/__init__.py, docker_images/paddlenlp/app/pipelines/summarization.py, docker_images/paddlenlp/requirements.txt, docker_images/paddlenlp/tests/test_api.py, docker_images/paddlenlp/tests/test_api_summarization.py
- upgrade version
- support summarization pipeline
- switch all unit test models to `PaddleCI` models
=> [PaddleNLP] support Summarization pipeline; upgrade version

docker_images/common/app/pipelines/summarization.py, docker_images/common/tests/test_api_summarization.py, docker_images/paddlenlp/app/pipelines/summarization.py, docker_images/paddlenlp/tests/test_api_summarization.py
Address comments from @osanseviero which came late in #160
=> [PaddleNLP] Address late comments in summarization

build_docker.py
Linked to https://github.com/huggingface/api-inference/pull/1239
Need to update part of the secrets (DEFAULT_HOSTNAME)
=> Preparing to move to internal registry.

.github/workflows/python-api-diffusers-cd.yaml, .github/workflows/python-api-fairseq-cd.yaml, .github/workflows/python-api-flair-cd.yml, .github/workflows/python-api-k2-cd.yaml, .github/workflows/python-api-paddlenlp-cd.yaml, .github/workflows/python-api-sklearn-cd.yaml, build_docker.py, docker_images/paddlenlp/requirements.txt
=> Updating cd scripts to include tailscale and be able to push to our

.github/workflows/python-api-quality.yaml, docker_images/diffusers/app/pipelines/text_to_image.py, docker_images/diffusers/requirements.txt
=> Adding negative_prompt to diffusers.

docker_images/sklearn/run_app.sh
Issue was that the environment was missing skops.
Currently this model is failing: https://huggingface.co/scikit-learn/tabular-playground
=> Fixing https://huggingface.co/scikit-learn/tabular-playground

docker_images/diffusers/app/pipelines/text_to_image.py
=> Enabling all kwargs for diffusers.

docker_images/diffusers/app/pipelines/image_to_image.py
when model doesn't have a config file `is_controlnet` has no default value
=> set is_controlnet default value

docker_images/common/app/pipelines/image_to_image.py, docker_images/common/tests/test_api_image_to_image.py, docker_images/diffusers/app/pipelines/image_to_image.py, docker_images/diffusers/tests/test_api_image_to_image.py, tests/test_dockers.py
rename api as discussed.
couldn't get the tests to run well without running with a GPU docker backend, is it normal?
=> rename img2img api params

docker_images/diffusers/Dockerfile, docker_images/diffusers/requirements.txt
found another issue
using an olde formers version
no need to use the prebuild since xformers is now available on pypi
=> Updade xformers

docker_images/diffusers/Dockerfile, docker_images/diffusers/app/main.py, docker_images/diffusers/prestart.sh, docker_images/diffusers/requirements.txt
- Enable HF transfer
- No more prestart script systematically run, means one less model load
- Logging when running prestart by hand
=> Diffusers image updates

docker_images/nemo/Dockerfile, docker_images/nemo/requirements.txt, docker_images/nemo/tests/test_api.py
PR to update the NeMo version to support Fast Conformer API Inference (+ switch to smaller model for CI)
cc @Vaibhavs10
=> Update NeMo version

docker_images/peft/app/pipelines/text_generation.py, docker_images/peft/requirements.txt
Fixed invalid response body, see below
=> Minor fix for PEFT

docker_images/peft/app/pipelines/text_generation.py, docker_images/peft/tests/test_api.py, docker_images/peft/tests/test_api_text_generation.py, tests/test_dockers.py
this was the reason why docker tests weren't working @Narsil
=> Added missing test to PEFT tests

docker_images/diffusers/app/pipelines/text_to_image.py
Swap DPM Solver to Euler A for better low step generalisation
=> Change default diffusion scheduler

docker_images/diffusers/app/lora.py, docker_images/diffusers/app/pipelines/text_to_image.py, docker_images/diffusers/requirements.txt
Depends on https://github.com/huggingface/api-inference-community/pull/335
=> LoRA mutualization: keep base model loaded, load/unload LoRA adapters on the fly

docker_images/diffusers/app/lora.py, docker_images/diffusers/app/pipelines/text_to_image.py
Root cause not yet precisely identified but this avoids expanding some issues between adapters
related to https://github.com/huggingface/diffusers/issues/5313
=> Remove fuse/unfuse

docker_images/diffusers/app/pipelines/image_to_image.py
more specifically to fix inference for:
stabilityai/stable-diffusion-xl-refiner-1.0
=> StableDiffusionXLImg2ImgPipeline support

docker_images/open_clip/app/pipelines/zero_shot_image_classification.py, docker_images/open_clip/requirements.txt
Add support for sigmoid scores for SigLIP models
=> Update OpenCLIP to latest version, bump other reqs

docker_images/open_clip/app/pipelines/zero_shot_image_classification.py
Fixes regression in probabilities for last update
=> Missed the exp() on logit scale for OpenCLIP update

docker_images/peft/requirements.txt, requirements.txt
The existing dependencies result in dependency conflict when starting the app locally.
=> Bumping huggingface-hub and accelerate for PEFT image dependencies

api_inference_community/hub.py, requirements.txt, tests/test_hub.py
could be used to fix https://github.com/huggingface/api-inference-community/issues/372
=> model info that works offline

docker_images/diffusers/app/lora.py, docker_images/diffusers/requirements.txt
broader exception type catch on fuse_lora
=> diffusers docker image: load lora uncaught errors

docker_images/speechbrain/app/common.py
Related to breaking change https://github.com/huggingface/api-inference-community/pull/416
=> Fix broken SpeechBrain API

Makefile, api_inference_community/routes.py, requirements.txt
No need to perform some inference that won't be fetched anyway
=> Discard a request if the caller already left

docker_images/diffusers/requirements.txt
Update diffusers to the latest main
=> Improve diffusers support
