.github/workflows/python-api-flair.yaml, docker_images/flair/app/pipelines/token_classification.py, docker_images/flair/requirements.txt
Rebuilt the old version, but since it's using a non pinned version of `flair` it can cause issues (Lack of Etag seems to be linked to `huggingface_hub` not flair though, but I have seen that there could be some small modifications needed too.? )
=> Updating flair to `0.11.1`

docker_images/sentence_transformers/Dockerfile, docker_images/sentence_transformers/GpuDockerfile, docker_images/sentence_transformers/requirements.txt
https://github.com/UKPLab/sentence-transformers/commit/16877a716b068828cd7f4d0a65ebe60ec3312ef0
We need the new version to pass the token correctly to be able to run private models for `sentence-transformers`.
Edited the dockerfiles for better layer caching
=> Need 2.2.2

docker_images/sklearn/README.md, tests/test_dockers.py
sklearn tests (tabular classification and regression) failed because the underlying model was using an older version (0.24). Now we use the latest version created via the `docker_images/sklearn/tests/generatos/run.sh` script.
Furthermore, for inference calls to these models to work, we need specific input data, which can now optionally be passed to the `framework_docker_test` function.
=> Sklearn docker tests update

docker_images/sklearn/run_app.sh
Now that the package is on conda-forge, we can add it to the `mamba install` command which also speeds up the load time of models.
xref: https://github.com/skops-dev/skops/issues/101
cc @BenjaminBossan @Narsil
=> ENH install api-inference-community from conda-forge for sklearn

docker_images/fairseq/requirements.txt
Updating the [version](https://github.com/facebookresearch/fairseq/commit/eda703798dcfde11c1ee517805c27e8698285d71) of fairseq to test new models in the [list](https://github.com/facebookresearch/fairseq/blob/d81fac8163364561fd6cd9d82b6ee1ba502c3526/fairseq/models/speech_to_text/xm_transformer.py#L493).
=> update the fairseq version to support more models

docker_images/fairseq/requirements.txt
Sync fairseq version with https://github.com/facebookresearch/fairseq/pull/4727/commits/37c1573bc3f0e206d2b0909d82c22b6bccb7fa4a to support vocoder on cpu devices
=> update fairseq version to support vocoder on cpu

docker_images/fairseq/requirements.txt
Sync version to solve the [ModuleNotFoundError: No module named 'fairseq.models.speech_to_text.modules issue](https://github.com/facebookresearch/fairseq/issues/4726) with the latest [PR](https://github.com/facebookresearch/fairseq/pull/4733)
=> update fairseq version

.github/workflows/python-api-flair-cd.yaml, build_docker.py
The goal is to automatically deploy on merge.
The helm prod chart lives in another repo, ideally we trigger
another action in this other repo (it's simpler). 
The building and uploading can happen here, we just need to add some secrets to this repo.
Feedback welcome on the approach.
Ideally I would like to have a single CD action, that would just check at the modified folders and deploy every folder hit in `docker_images`.
This seems doable however not highly stable (depends on the trigger of the action to get the correct git commands)
Requires: https://github.com/huggingface/api-inference/pull/1151
=> First step towards CD. (Only flair for now)

docker_images/fairseq/app/pipelines/audio_to_audio.py
Some changes in this commit:
- Add `beam` and `max_len_a` configuration to fix generation issue to avoid duration limitations of translation results.
- Replace the unit text output of S2UT models with an empty string. 
- Remove `cpu=true`, local test passed with `pytest -sv --rootdir docker_images/fairseq/ docker_images/fairseq/` , maybe need to further check after it is deployed.
=> fix generation issue and remove unit text for s2ut models

docker_images/flair/requirements.txt
Update flair version to support word and transformer embeddings on widget and inference API.
Some models are only working with latest versions of flair.
For example: This [example of flair 0.11.3 model](https://huggingface.co/lighthousefeed/yoda-ner) only works with latest commit of the library.
You can check it here: [colab notebook](https://colab.research.google.com/drive/1EnL0IFLVN1FDO1x42r13A8oZsfdBcHPg?usp=sharing)
=> Update flair version to support latest models

docker_images/fairseq/app/pipelines/audio_to_audio.py, docker_images/fairseq/requirements.txt
Update the fairseq version to https://github.com/facebookresearch/fairseq/pull/4776 and a small change for reading the model id from hf repo
Test passed with `pytest -sv --rootdir docker_images/fairseq/ docker_images/fairseq/`
=> Update the fairseq version for hk models

docker_images/sklearn/app/pipelines/common.py, docker_images/sklearn/app/pipelines/tabular_classification.py, docker_images/sklearn/app/pipelines/text_classification.py, docker_images/sklearn/tests/test_api_tabular_classification.py, docker_images/sklearn/tests/test_api_tabular_regression.py, docker_images/sklearn/tests/test_api_text_classification.py
See #92
When calling the prediction pipeline produces warnings, it is treated as an error. This includes situations where the model output *might* be correct but we're not sure, most notably when there is a mismatch of the version of the loaded sklearn model and the sklearn version of the runtime.
Although we still return the model outputs to the user, we don't show them what warnings were actually encountered. This makes debugging difficult. Therefore, we want to show them the warnings.
This requires two changes. First, we need to add the encountered warnings to the response. Second, we need to display these warnings. This PR implements the first step.
On top of that, this PR introduces a small refactoring to reduce the amount of code duplication (see the last paragraph of [this …
=> Add warnings to error response for sklearn Pipelines

.github/workflows/python-api-export-tasks.yaml, scripts/export_tasks.py
Context: https://huggingface.slack.com/archives/C02ERUY9TKK/p1669743642830359
=> Add export tasks

docker_images/sklearn/app/pipelines/common.py
My previous PR was raising a UserWarning which results in inference API to break when there's no config.json in scikit-learn models. (which applies to all the sklearn models not uploaded with skops) so I swapped raising `UserWarning` with `warnings.warn` instead.
*(to me it doesn't make any sense when a widget doesn't include example input anyway which doesn't come with a scikit-learn model itself but it's discussion for another day)*
=> Fix backwards compatibility for inference API for scikit-learn models with no config

docker_images/diffusers/app/pipelines/text_to_image.py
As we always have a batch size of 1 for a single prompt, let's improve compatibility with kwargs. For instance, use:
```
inputs: "...prompt",
parameters {
negative_prompt: "....negative_prompt"
}
```
instead of:
```
inputs: "...prompt",
parameters {
negative_prompt: ["....negative_prompt"]
}
```
currently if you don't send negative_prompt as a list you get this error
```
{"error":"`negative_prompt` should be the same type to `prompt`, but got <class 'str'> != <class 'list'>."}
```
=> Change input format on call for better compatibility with kwargs

docker_images/sentence_transformers/requirements.txt
Should fix https://huggingface.co/sentence-transformers/paraphrase-xlm-r-multilingual-v1
Which is currently bugged (it seems that the old huggingface_hub is not properly respecting the HEAD/GET requests with tokens which are necessary for sentence-transformers, leading to BAD requests)
=> Upgradign sentence transformers (huggingface_hub version).

docker_images/diffusers/app/pipelines/image_to_image.py, docker_images/diffusers/requirements.txt, docker_images/diffusers/tests/test_api_image_to_image.py
@patrickvonplaten  Here is a summary:
Defer to the DiffusionPipeline for StableDiffusionImg2ImgPipeline, as AltDiffusionImg2ImgPipeline is currently throwing basic errors when passing **kwargs.
I am explicitly checking the `model_type` using the `config.json` and `model_index.json`, and loading the appropriate pipelines to support Img2Img on `[AltDiffusion, ControlNetModel, StableDiffusion, and InstructPix2Pix]`
All tests `pytest -sv --rootdir docker_images/diffusers docker_images/diffusers` are now passing. 🙌
You can also add extra models for testing locally:
```python
TESTABLE_MODELS: Dict[str, List[str]] = {
"text-to-image": ["hf-internal-testing/tiny-stable-diffusion-pipe-no-safety"],
"image-to-image": [
"hf-internal-testing/tiny-controlnet", …
```
=> More fixes img2img

docker_images/diffusers/Dockerfile, docker_images/diffusers/app/pipelines/image_to_image.py, docker_images/diffusers/app/pipelines/text_to_image.py, docker_images/diffusers/requirements.txt, requirements.txt
This is an attempt to add a few more im2img pipelines.
This PR adds support for `StableDiffusionImageVariationPipeline`, `StableUnCLIPImg2ImgPipeline` and finally `FlaxStableDiffusionControlNetPipeline` 
Two points of concern:
1. I'm using Diffusers 0.17.0.dev0 - git+https://github.com/huggingface/diffusers@main since it has support for the new`FlaxStableDiffusionControlNetPipeline`, and PyTorch 2.0
2. Running Flax/Jax on a GPU container was a bit challenging, I'm not sure if this will be compatible with our API backend, currently to make it work on my test enviroment I needed to use `nvidia/cuda:11.7.1-devel-ubuntu22.04` and `jax[cuda11_cudnn82]` the models take a considerable time to load, then the inference time was reasonable, using `Tesla V100 16VRAM` @Narsil wdyt? 
If the Flax is to …
=> Add more img2img Pipelines

docker_images/diffusers/app/pipelines/image_to_image.py
Added
* StableDiffusionDepth2ImgPipeline
* StableDiffusionLatentUpscalePipeline
* StableDiffusionUpscalePipeline
@patrickvonplaten is there any other Image2Image Pipeline worth adding? otherwise I think we've covered all the coolest ones 
In case you want to test, I have duplicated models with right `image-to-image` tag
```python 
"image-to-image": [
"hf-internal-testing/tiny-controlnet",
"hf-internal-testing/tiny-stable-diffusion-pix2pix",
"radames/stable-diffusion-v1-5-img2img",  # stable diffusion
"radames/AltDiffusion-m9-img2img",  # alt diffusion
"timbrooks/instruct-pix2pix",  # instruct pix2pix
"lllyasviel/sd-controlnet-depth",  # controlnet
"lllyasviel/control_v11f1e_sd15_tile",  # controlnet
"lambdalabs/sd-image-variations-diffusers",  # StableDiffusionImageVariationPipeline …
```
=> add more img2img

docker_images/diffusers/app/idle.py, docker_images/diffusers/app/main.py, docker_images/diffusers/app/pipelines/image_to_image.py, docker_images/diffusers/app/pipelines/text_to_image.py, docker_images/diffusers/app/timing.py
Allows to free gpu resources for example and the cost to move it back to gpu if already loaded in mem is only ~3s. 
Add some overcommit possibility when serving several models on a single gpu at once
tl;dr
The Api Inference infra now serves most diffusion models on shared gpus: thus we can simultaneously serve the very same number of diffusion models as before with twice less hosts dedicated for this. However, we could improve the stacking models on a single gpu by adding some overcommit possibility. This is the point of the pr: releasing the gpu resources when idle, more precisely the gpu memory that is currently the main factor preventing us from increasing the model stacking ratio on a gpu. In this pr the Guvicorn worker is simply killed as soon as we see that the model did not receive …
=> Periodically unload model / reset worker if no request was received for a while

.github/workflows/python-api-bertopic.yaml
Fixes a typo in the naming of bertopic. Failing tests related to a different file (can open a seperate PR to fix that)
=> fix typo in BERTopic path

docker_images/diffusers/app/idle.py, docker_images/diffusers/app/pipelines/image_to_image.py, docker_images/diffusers/app/pipelines/text_to_image.py, docker_images/diffusers/requirements.txt
Notes:
* removed the `AttnProcessor2_0` since it's enabled by default if using PyTorch 2.0 right?
* had to break `kwargs`  for the prior, since it will throw in case user send args, such as `width`, `strength`, etc.
* for each pipeline we can set a default  `num_inference_steps` @yiyixuxu please let me know if 100 for img2img works, since I saw it on your example. `num_images_per_prompt` is always 1
<details>
<summary> Notes for testing</summary>
You can use these models, and set `api-inference-community/docker_images/diffusers/tests/test_api.py` temporary on your local env
```python
TESTABLE_MODELS: Dict[str, List[str]] = {
"text-to-image": [
"hf-internal-testing/tiny-stable-diffusion-pipe-no-safety",
"kandinsky-community/kandinsky-2-1",
],
"image-to-image": [ …
```
=> add support for Kandinsky

api_inference_community/routes.py, api_inference_community/validation.py, tests/test_audio.py, tests/test_routes.py
This ensures that returned payload is in the format that a client can accept.
- Added way to specify accept header mime types for returned image and audio content in the specified format
- Added unit tests for text-to-speech, audio-to-audio, and text-to-image tasks
=> feat: added mime accept headers

docker_images/flair/requirements.txt
Hi,
Flair team here :hugs: 
With this PR the latest commit of Flair is used for the inference container.
We need this update to fix broken models incl. recently fine-tuned models with recent Flair version.
This update e.g. fixes:
* `'dict' object has no attribute 'embedding_length'` error from [this model](https://huggingface.co/flair/ner-german?text=George+Washington+ging+dann+nach+Washington)
* `No module named 'flair.trainers.plugins'` error from [this model](https://huggingface.co/hmteams/flair-hipe-2022-ajmc-en?text=Cp+.+Eur+.+Phoen+.+240+%2C+1+%2C+%CE%B1%E1%BC%B7%CE%BC%CE%B1+ddiov+%CF%86%CE%BB%CE%AD%CE%B3%CE%AD%CE%B9+.)
I locally tested the container and all these errors are gone - and ensured that is also works with already [other …
=> Flair: Bump version

api_inference_community/routes.py
This intermediate pr is required to release a new lib version (0.0.33) that would then be used in the following pr:
https://github.com/huggingface/api-inference-community/pull/334
=> Update api_inference_community lib to support a new header

docker_images/diffusers/Dockerfile, docker_images/diffusers/app/healthchecks.py, docker_images/diffusers/prestart.sh, docker_images/diffusers/requirements.txt
side service that will be used to serve some metrics used by custom hpa. open to discussion, not sure we actually want to have it in the following repo but we may prefer moving it in a dependency lib instead
=> feat diffusers docker image: possibility to spawn a side server reporting whether the inference service is busy or not

docker_images/diffusers/app/pipelines/text_to_image.py
This PR aims to give users the ability to swap schedulers.
=> Let users swap schedulers

docker_images/speechbrain/Dockerfile, docker_images/speechbrain/app/pipelines/audio_classification.py, docker_images/speechbrain/app/pipelines/audio_to_audio.py, docker_images/speechbrain/app/pipelines/automatic_speech_recognition.py, docker_images/speechbrain/app/pipelines/text2text_generation.py, docker_images/speechbrain/app/pipelines/text_to_speech.py, docker_images/speechbrain/requirements.txt
Hello there,
This PR is because SB is now stable and the v1 is released. 
I'd like to mention that I ran the tests, and some of them fail, but I simply can't understand why as I was not able to get the exception. I tested the code corresponding to the test locally, on the same environment than the test, and it works. 
I ran `pytest -v --tb=native -sv --rootdir docker_images/speechbrain/ docker_images/speechbrain/`. Weirdly, all the interfaces work when I try them locally :-( 
I also tried to just remove entirely the content of the __call__, just returning a dummy expected variable of the right type, and the tests would still fail, which sounds surprising to me.
Many thanks!
=> Update to SpeechBrain v1.0

docker_images/diffusers/requirements.txt
This upgrades diffusers to the latest main to provide initial SD3 support. 
SD3 LoRAs are not yet supported due to https://github.com/huggingface/diffusers/issues/8615 
Plan is to wait on the response of the diffusers team on how easy/what's the prio to implement `fuse_lora` on SD3. If it is not coming soon I'll send another PR changing the logic to support load/unloading LoRAs without fusing for SD3
=> Initial SD3 support

docker_images/diffusers/requirements.txt
The pinned old Transformers seemed to be breaking the pipeline loading.
Also upgraded `diffusers` to include this PR: https://github.com/huggingface/diffusers/pull/8616
=> Update transformers, diffusers and accelerate for `diffusers`

docker_images/diffusers/Dockerfile, docker_images/diffusers/requirements.txt
fix for sd3
```
T5Converter requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.
```
=> Protobuf required dependency

docker_images/diffusers/requirements.txt
Support SD3 LoRA fusion as https://github.com/huggingface/diffusers/pull/8616 didn't make it to the [0.29.2](https://github.com/huggingface/diffusers/releases/tag/v0.29.2) patch release
=> Upgrade diffusers to main

docker_images/diffusers/requirements.txt
Upgrade diffusers to support FLUX.1 models in the inference API (and hence get the widget working)
=> Support FLUX models in diffusers

.github/workflows/python-api-diffusers-cd.yaml
- Do not push to internal registry anymore (no access), use ghcr instead
- Do not use tailscale (no need, if we do not push to internal registry)
- Remove api-inference trigger -> needs rework
- TODO: adapt other frameworks as well
=> Refactor diffusers CD

docker_images/diffusers/requirements.txt
Depends on https://github.com/huggingface/api-inference-community/pull/447
=> diffusers docker image: dependencies update

api_inference_community/routes.py
example:
task: image-to-image
if the user provides sth that cannot be parsed by PIL (eg an image) PIL will raise an OSError (and EnvironmentError is an alias for OSError, kept for backward compat) But actually this "OSError" is due to some bad payload provided by the user. So let's consider that we have filtered all internal errors when loading pipeline
=> status code: input parsing, no EnvironmentError case handling
